<script setup lang="ts">
import { computed, onMounted, onBeforeUnmount, ref } from 'vue'
import type { MediaImage } from '../shared/admin'
import { maxImageBytes } from '../shared/admin'
import { guideApi, uploadFile, imageMarkdown, validateImage } from './guide-api'
const props=defineProps<{csrf:string;selectable?:boolean}>()
const emit=defineEmits<{error:[e:unknown];select:[image:MediaImage,alt:string];busy:[v:boolean]}>()
const images=ref<MediaImage[]>([]),query=ref(''),busy=ref(false),loading=ref(true),progress=ref(0),notice=ref(''),input=ref<HTMLInputElement>(),alt=ref('')
const lifetime=new AbortController();let upload:AbortController|undefined
const visible=computed(()=>images.value.filter(i=>i.name.toLowerCase().includes(query.value.toLowerCase())))
async function load(){loading.value=true;try{images.value=(await guideApi<{images:MediaImage[]}>('/api/admin/images',{signal:lifetime.signal})).images}catch(e){if(!lifetime.signal.aborted)emit('error',e)}finally{loading.value=false}}
async function send(event:Event){const files=Array.from((event.target as HTMLInputElement).files??[]);if(!files.length)return;busy.value=true;emit('busy',true);notice.value='';upload=new AbortController()
try{for(const file of files){if(file.size>maxImageBytes){notice.value=`${file.name} 超过 10 MiB，请压缩后上传。`;break}await validateImage(file);progress.value=0;await uploadFile('/api/admin/images?name='+encodeURIComponent(file.name),file,{csrf:props.csrf,signal:upload.signal,progress:v=>progress.value=v})}await load();if(!notice.value)notice.value='图片已上传，可随时插入正文。'}catch(e){if(upload.signal.aborted)notice.value='上传已取消，已完成的图片仍保留。';else emit('error',e)}finally{busy.value=false;emit('busy',false);if(input.value)input.value.value=''}}
async function choose(image:MediaImage){if(props.selectable){emit('select',image,alt.value||image.name);return}try{await navigator.clipboard.writeText(imageMarkdown(image.url,alt.value||image.name));notice.value='图片 Markdown 已复制，可粘贴到正文。'}catch{notice.value='复制未完成，请使用下方图片地址。'}}
onMounted(load);onBeforeUnmount(()=>{lifetime.abort();upload?.abort();emit('busy',false)})
</script>
<template><section class="media-library" :aria-busy="busy"><div class="editor-heading"><div><h2>图片库</h2><p>PNG、JPEG、WebP，每张最多 10 MiB。</p></div><div class="admin-actions"><input ref="input" class="file-input" type="file" accept="image/png,image/jpeg,image/webp" multiple aria-label="选择图片文件" :disabled="busy" @change="send" /><button class="button primary" :disabled="busy" @click="input?.click()">上传图片</button><button v-if="busy" class="button secondary" @click="upload?.abort()">取消上传</button><button v-else class="button secondary" @click="load">刷新</button></div></div><div v-if="busy" class="upload-progress" role="status"><progress :value="progress" max="100"></progress>{{progress}}% · {{progress===100?'正在保存…':'正在上传…'}}</div><p v-if="notice" class="admin-success" role="status">{{notice}}</p><div class="chapter-fields"><label>查找图片<input v-model="query" type="search" placeholder="图片名称" /></label><label>图片说明<input v-model="alt" maxlength="200" placeholder="用于正文和无障碍阅读，可选" /></label></div><p v-if="loading" role="status">正在加载图片…</p><p v-if="!images.length&&!busy&&!loading" class="admin-empty">上传第一张图片，或在正文中直接粘贴、拖入图片。</p><div class="media-grid"><article v-for="image in visible" :key="image.url" class="media-card"><a :href="image.url" target="_blank" rel="noopener"><img :src="image.url" :alt="image.name" loading="lazy" /></a><strong>{{image.name}}</strong><small>{{image.width}} × {{image.height}} · {{(image.size/1024).toFixed(0)}} KiB</small><button class="button secondary" :disabled="busy" @click="choose(image)">{{selectable?'插入图片':'复制 Markdown'}}</button><details><summary>图片地址</summary><code>{{image.url}}</code></details></article></div></section></template>
